services:
  embed:
    container_name: embed_service
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    volumes:
      - ./data:/data
    command: ["--model-id", "BAAI/bge-small-en-v1.5"]
  rerank:
    container_name: rerank_service
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    volumes:
      - ./data:/data
    command: ["--model-id", "mixedbread-ai/mxbai-rerank-base-v1"]
  rag_service:
    container_name: rag_service
    build:
      context: .
    depends_on:
      - embed
      - rerank
    environment:
      EMB_MODEL: BAAI/bge-small-en-v1.5
